name: '基础步骤'
description: '公共的检出、Python 环境和依赖安装'
runs:
  using: composite
  steps:
    - name: 设置 Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 缓存 Python 依赖
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          **/__pycache__
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 安装依赖
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi